export type LocalModelUse = "voice" | "nodeagent" | "code" | "vision" | "embedding" | "reasoning";
export type HardwareTier = "tiny" | "laptop" | "workstation" | "high_vram" | "cloud_or_lab";
export type ModelBucket = "latest_local" | "latest_edge" | "practical_stable" | "specialized" | "embedding" | "cloud_only_reference";
export type ModelAvailability = "local" | "local_pre_release" | "local_lab" | "cloud_only";

export type LocalModelOption = {
  id: string;
  label: string;
  family: string;
  ollamaModel: string;
  parameterSize: string;
  hardwareTier: HardwareTier;
  recommendedFor: LocalModelUse[];
  bucket: ModelBucket;
  availability: ModelAvailability;
  contextWindow?: string;
  input?: "text" | "text_image" | "embedding";
  licenseNote?: string;
  notes: string;
  pull: string;
  sourceUrl: string;
};

export const MODEL_CATALOG_REFRESHED_AT = "2026-07-04";

export const LOCAL_MODEL_OPTIONS: LocalModelOption[] = [
  // Latest local/edge families first. Gemma 4 is now the primary default family.
  {
    id: "gemma4_e2b",
    label: "Gemma 4 E2B — latest edge voice/room-state default",
    family: "Google Gemma 4",
    ollamaModel: "gemma4:e2b",
    parameterSize: "2.3B effective / 5.1B loaded",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent", "vision", "reasoning"],
    bucket: "latest_edge",
    availability: "local",
    contextWindow: "128K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Newest Gemma edge choice for the voice side: use it for transcript-to-action, room-state classification, and terse utterance generation. The reducer still prevents acknowledgement loops.",
    pull: "ollama pull gemma4:e2b",
    sourceUrl: "https://ollama.com/library/gemma4",
  },
  {
    id: "gemma4_e4b",
    label: "Gemma 4 E4B — stronger edge voice/NodeAgent model",
    family: "Google Gemma 4",
    ollamaModel: "gemma4:e4b",
    parameterSize: "4.5B effective / 8B loaded",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent", "vision", "reasoning"],
    bucket: "latest_edge",
    availability: "local",
    contextWindow: "128K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Better local default when E2B is too shallow. Good for three-agent room-state continuation plus short NodeAgent artifacts.",
    pull: "ollama pull gemma4:e4b",
    sourceUrl: "https://ollama.com/library/gemma4",
  },
  {
    id: "gemma4_12b",
    label: "Gemma 4 12B — latest laptop/workstation NodeAgent default",
    family: "Google Gemma 4",
    ollamaModel: "gemma4:12b",
    parameterSize: "12B dense",
    hardwareTier: "workstation",
    recommendedFor: ["nodeagent", "code", "vision", "reasoning"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Newest mid-sized Gemma 4 model. Use it as the stronger local NodeAgent model for artifact synthesis, code review, and multimodal document/image reasoning.",
    pull: "ollama pull gemma4:12b",
    sourceUrl: "https://ollama.com/library/gemma4",
  },
  {
    id: "gemma4_26b",
    label: "Gemma 4 26B-A4B — MoE local reasoning/agent model",
    family: "Google Gemma 4",
    ollamaModel: "gemma4:26b",
    parameterSize: "25.2B total / 3.8B active MoE",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code", "vision", "reasoning"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Gemma 4 MoE option for harder reasoning/code tasks when you have enough local memory. Better for reviewer/planner agents than low-latency voice output.",
    pull: "ollama pull gemma4:26b",
    sourceUrl: "https://ollama.com/library/gemma4",
  },
  {
    id: "gemma4_31b",
    label: "Gemma 4 31B — dense local/lab reasoning model",
    family: "Google Gemma 4",
    ollamaModel: "gemma4:31b",
    parameterSize: "30.7B dense",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code", "vision", "reasoning"],
    bucket: "latest_local",
    availability: "local_lab",
    contextWindow: "256K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Strong dense Gemma 4 option for local/lab NodeAgent runs. Keep it out of weak-laptop defaults.",
    pull: "ollama pull gemma4:31b",
    sourceUrl: "https://ollama.com/library/gemma4",
  },
  {
    id: "gemma3n_e2b",
    label: "Gemma 3n E2B — older tiny everyday-device fallback",
    family: "Google Gemma 3n",
    ollamaModel: "gemma3n:e2b",
    parameterSize: "2B effective",
    hardwareTier: "tiny",
    recommendedFor: ["voice", "nodeagent"],
    bucket: "practical_stable",
    availability: "local",
    contextWindow: "32K",
    input: "text",
    notes: "Older tiny fallback for the voice-agent side when Gemma 4 is too heavy or unavailable.",
    pull: "ollama pull gemma3n:e2b",
    sourceUrl: "https://ollama.com/library/gemma3n",
  },
  {
    id: "gemma3n_e4b",
    label: "Gemma 3n E4B — older everyday-device fallback",
    family: "Google Gemma 3n",
    ollamaModel: "gemma3n:e4b",
    parameterSize: "4B effective",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent"],
    bucket: "practical_stable",
    availability: "local",
    contextWindow: "32K",
    input: "text",
    notes: "Older fallback when you need something smaller than Gemma 4 E4B for room-state classification or short artifact synthesis.",
    pull: "ollama pull gemma3n:e4b",
    sourceUrl: "https://ollama.com/library/gemma3n",
  },
  {
    id: "ministral3_3b",
    label: "Ministral 3 3B — latest edge agent model",
    family: "Mistral Ministral 3",
    ollamaModel: "ministral-3:3b",
    parameterSize: "3B",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent", "vision"],
    bucket: "latest_edge",
    availability: "local_pre_release",
    contextWindow: "256K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Edge-oriented model with vision, tool use, JSON output, multilingual support, and a 256K context window. Requires current/pre-release Ollama support.",
    pull: "ollama pull ministral-3:3b",
    sourceUrl: "https://ollama.com/library/ministral-3",
  },
  {
    id: "ministral3_8b",
    label: "Ministral 3 8B — best latest laptop NodeAgent default",
    family: "Mistral Ministral 3",
    ollamaModel: "ministral-3:8b",
    parameterSize: "8.9B",
    hardwareTier: "laptop",
    recommendedFor: ["nodeagent", "voice", "vision", "code"],
    bucket: "latest_edge",
    availability: "local_pre_release",
    contextWindow: "256K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Best latest drop-in for NodeAgent if you want a small model with native function calling, JSON output, long context, and vision.",
    pull: "ollama pull ministral-3:8b",
    sourceUrl: "https://ollama.com/library/ministral-3:8b",
  },
  {
    id: "ministral3_14b",
    label: "Ministral 3 14B — stronger edge NodeAgent/vision model",
    family: "Mistral Ministral 3",
    ollamaModel: "ministral-3:14b",
    parameterSize: "14B",
    hardwareTier: "workstation",
    recommendedFor: ["nodeagent", "code", "vision"],
    bucket: "latest_edge",
    availability: "local_pre_release",
    contextWindow: "256K",
    input: "text_image",
    licenseNote: "Apache-2.0",
    notes: "Use when you can spare more memory and want better artifact synthesis while staying in the edge-optimized family.",
    pull: "ollama pull ministral-3:14b",
    sourceUrl: "https://ollama.com/library/ministral-3:14b",
  },
  {
    id: "qwen3_6_27b",
    label: "Qwen3.6 27B — latest Qwen agentic coding/thinking model",
    family: "Qwen3.6",
    ollamaModel: "qwen3.6:27b",
    parameterSize: "27B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code", "vision", "reasoning"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text_image",
    notes: "Current Qwen-family upgrade for agentic coding, thinking preservation, tool use, and multimodal NodeAgent workflows.",
    pull: "ollama pull qwen3.6:27b",
    sourceUrl: "https://ollama.com/library/qwen3.6:27b",
  },
  {
    id: "qwen3_6_35b_a3b",
    label: "Qwen3.6 35B-A3B — MoE coding/reasoning variant",
    family: "Qwen3.6",
    ollamaModel: "qwen3.6:35b-a3b-q4_K_M",
    parameterSize: "35B total / 3B active MoE",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code", "vision", "reasoning"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text_image",
    notes: "Good candidate when you want an MoE-style Qwen3.6 model for multi-step artifact loops without moving to 100B+ weights.",
    pull: "ollama pull qwen3.6:35b-a3b-q4_K_M",
    sourceUrl: "https://ollama.com/library/qwen3.6/tags",
  },
  {
    id: "nemotron_cascade_2_30b",
    label: "Nemotron-Cascade-2 30B-A3B — open MoE reasoning/agent model",
    family: "NVIDIA Nemotron",
    ollamaModel: "nemotron-cascade-2:30b-a3b-q4_K_M",
    parameterSize: "30B total / 3B active MoE",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "reasoning", "code"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text",
    notes: "Open MoE model for reasoning and agentic tasks; good as a local orchestrator/reviewer for NodeAgent plans.",
    pull: "ollama pull nemotron-cascade-2:30b-a3b-q4_K_M",
    sourceUrl: "https://ollama.com/library/nemotron-cascade-2",
  },
  {
    id: "mistral_medium_3_5_128b",
    label: "Mistral Medium 3.5 128B — latest local/lab flagship",
    family: "Mistral Medium 3.5",
    ollamaModel: "mistral-medium-3.5:128b",
    parameterSize: "128B",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["nodeagent", "code", "vision", "reasoning"],
    bucket: "latest_local",
    availability: "local_lab",
    contextWindow: "256K",
    input: "text_image",
    notes: "Flagship unified instruct/reasoning/coding model. Not a normal laptop default; use on a beefy local box or lab machine.",
    pull: "ollama pull mistral-medium-3.5:128b",
    sourceUrl: "https://ollama.com/library/mistral-medium-3.5",
  },
  {
    id: "glm_4_7_flash",
    label: "GLM-4.7-Flash 30B-A3B — latest lightweight Z.ai agent model",
    family: "Z.ai GLM",
    ollamaModel: "glm-4.7-flash",
    parameterSize: "30B total / 3B active MoE",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code", "reasoning"],
    bucket: "latest_local",
    availability: "local_pre_release",
    contextWindow: "200K+",
    input: "text",
    notes: "Strong 30B-class MoE option for lightweight agent deployment; Ollama notes may require a newer/pre-release runtime.",
    pull: "ollama pull glm-4.7-flash",
    sourceUrl: "https://ollama.com/library/glm-4.7-flash",
  },
  {
    id: "glm_5",
    label: "GLM-5 — huge open-weight agentic engineering model",
    family: "Z.ai GLM",
    ollamaModel: "glm-5",
    parameterSize: "744B total / 40B active MoE",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["nodeagent", "code", "reasoning"],
    bucket: "latest_local",
    availability: "local_lab",
    contextWindow: "long context",
    input: "text",
    notes: "Lab-scale local model for complex reasoning, coding, and agentic tasks. Include as a reference, not as a laptop default.",
    pull: "ollama pull glm-5",
    sourceUrl: "https://ollama.com/library/glm-5",
  },
  {
    id: "glm_5_1",
    label: "GLM-5.1 — flagship agentic engineering model",
    family: "Z.ai GLM",
    ollamaModel: "glm-5.1",
    parameterSize: "frontier MoE",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["nodeagent", "code", "reasoning"],
    bucket: "latest_local",
    availability: "local_lab",
    contextWindow: "long context",
    input: "text",
    notes: "Latest GLM-family engineering-agent reference. Use only on serious local/lab hardware or a compatible remote Ollama backend.",
    pull: "ollama pull glm-5.1",
    sourceUrl: "https://ollama.com/library/glm-5.1",
  },
  {
    id: "mistral_small_3_2",
    label: "Mistral Small 3.2 24B — repetition/function-calling fix",
    family: "Mistral Small 3.2",
    ollamaModel: "mistral-small3.2:24b",
    parameterSize: "24B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "vision", "code"],
    bucket: "latest_local",
    availability: "local",
    input: "text_image",
    notes: "Still highly relevant because it explicitly improves instruction following, function calling, and repetition behavior — exactly the anti-loop failure mode.",
    pull: "ollama pull mistral-small3.2:24b",
    sourceUrl: "https://ollama.com/library/mistral-small3.2",
  },
  {
    id: "magistral_24b",
    label: "Magistral 24B — Mistral reasoning reviewer/planner",
    family: "Mistral Magistral",
    ollamaModel: "magistral:24b",
    parameterSize: "24B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "reasoning", "code"],
    bucket: "latest_local",
    availability: "local",
    input: "text",
    licenseNote: "Apache-2.0",
    notes: "Mistral reasoning model; good as a local reviewer/planner agent behind the deterministic room reducer.",
    pull: "ollama pull magistral:24b",
    sourceUrl: "https://ollama.com/library/magistral",
  },
  {
    id: "gpt_oss_20b",
    label: "gpt-oss 20B — open-weight local reasoning/agent model",
    family: "OpenAI gpt-oss",
    ollamaModel: "gpt-oss:20b",
    parameterSize: "20B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code", "reasoning"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "128K",
    input: "text",
    notes: "Open-weight local model designed for reasoning, agentic tasks, and developer workflows.",
    pull: "ollama pull gpt-oss:20b",
    sourceUrl: "https://ollama.com/library/gpt-oss",
  },
  {
    id: "gpt_oss_120b",
    label: "gpt-oss 120B — larger open-weight local/lab reasoning model",
    family: "OpenAI gpt-oss",
    ollamaModel: "gpt-oss:120b",
    parameterSize: "120B",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["nodeagent", "code", "reasoning"],
    bucket: "latest_local",
    availability: "local_lab",
    contextWindow: "128K",
    input: "text",
    notes: "Large local/lab model for harder reasoning and agent runs. Keep out of laptop defaults.",
    pull: "ollama pull gpt-oss:120b",
    sourceUrl: "https://ollama.com/library/gpt-oss",
  },
  {
    id: "qwen3_coder_next",
    label: "Qwen3-Coder-Next — latest efficient coding-agent model",
    family: "Qwen3-Coder",
    ollamaModel: "qwen3-coder-next",
    parameterSize: "80B total / 3B active MoE",
    hardwareTier: "high_vram",
    recommendedFor: ["code", "nodeagent", "reasoning"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text",
    notes: "Coding-agent model optimized for local development and agentic coding workflows; good for NodeAgent code/edit loops when available in your Ollama install.",
    pull: "ollama pull qwen3-coder-next",
    sourceUrl: "https://ollama.com/library/qwen3-coder-next",
  },
  {
    id: "qwen3_coder_30b",
    label: "Qwen3-Coder 30B — practical agentic code model",
    family: "Qwen3-Coder",
    ollamaModel: "qwen3-coder:30b",
    parameterSize: "30B",
    hardwareTier: "high_vram",
    recommendedFor: ["code", "nodeagent"],
    bucket: "latest_local",
    availability: "local",
    contextWindow: "256K",
    input: "text",
    notes: "More practical local Qwen3-Coder option than the 480B lab model; use for repo tasks and structured code-agent runs.",
    pull: "ollama pull qwen3-coder:30b",
    sourceUrl: "https://ollama.com/library/qwen3-coder",
  },
  {
    id: "qwen3_coder_480b",
    label: "Qwen3-Coder 480B — most agentic Qwen code model, lab only",
    family: "Qwen3-Coder",
    ollamaModel: "qwen3-coder:480b",
    parameterSize: "480B",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["code", "nodeagent"],
    bucket: "latest_local",
    availability: "local_lab",
    input: "text",
    notes: "Official local tag exists, but the model is enormous and belongs on a lab machine, not the default demo path.",
    pull: "ollama pull qwen3-coder:480b",
    sourceUrl: "https://ollama.com/library/qwen3-coder",
  },
  {
    id: "devstral_small_2",
    label: "Devstral Small 2 24B — current software-engineering agent",
    family: "Mistral / All Hands Devstral",
    ollamaModel: "devstral-small-2",
    parameterSize: "24B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code"],
    bucket: "latest_local",
    availability: "local",
    input: "text",
    notes: "Specialized for tool use, codebase exploration, multi-file editing, and SWE-bench-style workflows.",
    pull: "ollama pull devstral-small-2",
    sourceUrl: "https://ollama.com/library/devstral-small-2",
  },
  {
    id: "devstral_2_123b",
    label: "Devstral 2 123B — larger codebase agent, lab only",
    family: "Mistral / All Hands Devstral 2",
    ollamaModel: "devstral-2:123b",
    parameterSize: "123B",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["nodeagent", "code"],
    bucket: "latest_local",
    availability: "local_lab",
    input: "text",
    notes: "Large code-agent model for repo-scale software tasks when you have serious local memory.",
    pull: "ollama pull devstral-2:123b",
    sourceUrl: "https://ollama.com/library/devstral-2",
  },
  {
    id: "deepseek_r1_8b_0528",
    label: "DeepSeek-R1 0528 8B — practical distilled reasoner",
    family: "DeepSeek-R1",
    ollamaModel: "deepseek-r1:8b",
    parameterSize: "8B distilled",
    hardwareTier: "laptop",
    recommendedFor: ["reasoning", "nodeagent"],
    bucket: "latest_local",
    availability: "local",
    input: "text",
    notes: "Good reasoning model for local task planning/review. Use it as a reviewer, not as the fastest voice speaker.",
    pull: "ollama pull deepseek-r1:8b",
    sourceUrl: "https://ollama.com/library/deepseek-r1:32b",
  },
  {
    id: "phi4_mini_reasoning",
    label: "Phi-4 Mini Reasoning — tiny logic-intensive model",
    family: "Microsoft Phi-4",
    ollamaModel: "phi4-mini-reasoning",
    parameterSize: "3.8B",
    hardwareTier: "laptop",
    recommendedFor: ["reasoning", "voice", "nodeagent"],
    bucket: "specialized",
    availability: "local",
    input: "text",
    notes: "Small local model for math/logic-heavy reasoning under memory constraints.",
    pull: "ollama pull phi4-mini-reasoning",
    sourceUrl: "https://ollama.com/library/phi4-mini-reasoning",
  },
  {
    id: "phi4_reasoning_vision_15b",
    label: "Phi-4 Reasoning Vision 15B — compact multimodal UI/doc reasoner",
    family: "Microsoft Phi-4",
    ollamaModel: "phi4-reasoning-vision:15b",
    parameterSize: "15B",
    hardwareTier: "high_vram",
    recommendedFor: ["vision", "reasoning", "nodeagent"],
    bucket: "specialized",
    availability: "local_pre_release",
    input: "text_image",
    notes: "Good fit for UI screenshots, receipts, diagrams, and document grounding if your local runner exposes the model. Kept specialized because Ollama tag availability can vary.",
    pull: "ollama pull phi4-reasoning-vision:15b",
    sourceUrl: "https://www.microsoft.com/en-us/research/blog/phi-4-reasoning-vision-and-the-lessons-of-training-a-multimodal-reasoning-model/",
  },
  {
    id: "lfm2_5_thinking_1_2b",
    label: "LFM2.5 Thinking 1.2B — ultra-fast local classifier/reasoner",
    family: "Liquid AI LFM2.5",
    ollamaModel: "lfm2.5-thinking",
    parameterSize: "1.2B",
    hardwareTier: "tiny",
    recommendedFor: ["voice", "reasoning", "nodeagent"],
    bucket: "specialized",
    availability: "local",
    input: "text",
    notes: "Tiny, fast reasoning model for low-latency room-state classification, loop-risk detection, and cheap local planner checks.",
    pull: "ollama pull lfm2.5-thinking",
    sourceUrl: "https://ollama.com/library/lfm2.5-thinking",
  },
  {
    id: "olmo_3_1_32b_instruct",
    label: "OLMo 3.1 32B Instruct — open science model",
    family: "Allen AI OLMo",
    ollamaModel: "olmo-3.1:32b-instruct",
    parameterSize: "32B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "reasoning"],
    bucket: "specialized",
    availability: "local",
    input: "text",
    notes: "Useful when you want a more open/science-friendly checkpoint lineage for local evaluation.",
    pull: "ollama pull olmo-3.1:32b-instruct",
    sourceUrl: "https://ollama.com/library/olmo-3.1:32b-instruct",
  },
  {
    id: "llama4_scout",
    label: "Llama 4 Scout — large multimodal MoE, not newest but current Meta line",
    family: "Meta Llama 4",
    ollamaModel: "llama4:scout",
    parameterSize: "16x17B MoE",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["nodeagent", "vision"],
    bucket: "specialized",
    availability: "local_lab",
    contextWindow: "10M",
    input: "text_image",
    notes: "Keep as an option for extreme-context multimodal experiments; it is not the fastest/latest laptop choice.",
    pull: "ollama pull llama4:scout",
    sourceUrl: "https://ollama.com/library/llama4/tags",
  },
  // Practical stable baselines. These remain useful but should not be called the latest.
  {
    id: "llama3_2_1b",
    label: "Llama 3.2 1B — stable tiny fallback",
    family: "Meta Llama 3.2",
    ollamaModel: "llama3.2:1b",
    parameterSize: "1B",
    hardwareTier: "tiny",
    recommendedFor: ["voice"],
    bucket: "practical_stable",
    availability: "local",
    input: "text",
    notes: "Stable weak-laptop fallback for utterance shaping/classification. Not latest, but still useful.",
    pull: "ollama pull llama3.2:1b",
    sourceUrl: "https://ollama.com/library/llama3.2",
  },
  {
    id: "llama3_2_3b",
    label: "Llama 3.2 3B — stable low-latency voice fallback",
    family: "Meta Llama 3.2",
    ollamaModel: "llama3.2:3b",
    parameterSize: "3B",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent"],
    bucket: "practical_stable",
    availability: "local",
    input: "text",
    notes: "Not latest, but still a dependable voice-agent baseline because the reducer owns the task state.",
    pull: "ollama pull llama3.2:3b",
    sourceUrl: "https://ollama.com/library/llama3.2",
  },
  {
    id: "gemma3_4b_qat",
    label: "Gemma 3 4B QAT — stable compact vision baseline",
    family: "Google Gemma 3",
    ollamaModel: "gemma3:4b-it-qat",
    parameterSize: "4B",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent", "vision"],
    bucket: "practical_stable",
    availability: "local",
    contextWindow: "128K",
    input: "text_image",
    notes: "Not the newest Gemma entry, but compact and useful for local multimodal smoke tests.",
    pull: "ollama pull gemma3:4b-it-qat",
    sourceUrl: "https://ollama.com/library/gemma3",
  },
  {
    id: "qwen3_4b",
    label: "Qwen3 4B — stable small NodeAgent fallback",
    family: "Qwen3",
    ollamaModel: "qwen3:4b",
    parameterSize: "4B",
    hardwareTier: "laptop",
    recommendedFor: ["voice", "nodeagent"],
    bucket: "practical_stable",
    availability: "local",
    input: "text",
    notes: "Stable small agent baseline. Use when latest edge models are too heavy or unavailable.",
    pull: "ollama pull qwen3:4b",
    sourceUrl: "https://ollama.com/library/qwen3",
  },
  {
    id: "qwen3_30b",
    label: "Qwen3 30B-A3B — stable MoE agent fallback",
    family: "Qwen3",
    ollamaModel: "qwen3:30b",
    parameterSize: "30B total / 3B active MoE",
    hardwareTier: "workstation",
    recommendedFor: ["nodeagent", "code", "reasoning"],
    bucket: "practical_stable",
    availability: "local",
    contextWindow: "256K",
    input: "text",
    notes: "Still useful as a stable MoE agent model, but Qwen3.6 should be tried first for latest Qwen behavior.",
    pull: "ollama pull qwen3:30b",
    sourceUrl: "https://ollama.com/library/qwen3",
  },
  {
    id: "qwen2_5_coder_7b",
    label: "Qwen2.5-Coder 7B — stable practical code model",
    family: "Qwen2.5-Coder",
    ollamaModel: "qwen2.5-coder:7b",
    parameterSize: "7B",
    hardwareTier: "laptop",
    recommendedFor: ["nodeagent", "code"],
    bucket: "practical_stable",
    availability: "local",
    contextWindow: "32K",
    input: "text",
    notes: "Not latest, but still a very practical local code patch/debug model.",
    pull: "ollama pull qwen2.5-coder:7b",
    sourceUrl: "https://ollama.com/library/qwen2.5-coder",
  },
  {
    id: "qwen2_5_coder_32b",
    label: "Qwen2.5-Coder 32B — stable stronger code model",
    family: "Qwen2.5-Coder",
    ollamaModel: "qwen2.5-coder:32b",
    parameterSize: "32B",
    hardwareTier: "high_vram",
    recommendedFor: ["nodeagent", "code"],
    bucket: "practical_stable",
    availability: "local",
    contextWindow: "32K",
    input: "text",
    notes: "Strong non-latest code model for repository edits when Qwen3-Coder is too massive.",
    pull: "ollama pull qwen2.5-coder:32b",
    sourceUrl: "https://ollama.com/library/qwen2.5-coder",
  },
  // Embeddings for NodeAgent retrieval.
  {
    id: "nomic_embed_text",
    label: "nomic-embed-text — local embeddings for NodeAgent retrieval",
    family: "Nomic",
    ollamaModel: "nomic-embed-text",
    parameterSize: "embedding",
    hardwareTier: "tiny",
    recommendedFor: ["embedding"],
    bucket: "embedding",
    availability: "local",
    input: "embedding",
    notes: "Embedding-only model for local vector search/RAG. Do not use as the chat model.",
    pull: "ollama pull nomic-embed-text",
    sourceUrl: "https://ollama.com/library/nomic-embed-text",
  },
  {
    id: "snowflake_arctic_embed2",
    label: "snowflake-arctic-embed2 — multilingual local embeddings",
    family: "Snowflake Arctic Embed",
    ollamaModel: "snowflake-arctic-embed2",
    parameterSize: "568M embedding",
    hardwareTier: "tiny",
    recommendedFor: ["embedding"],
    bucket: "embedding",
    availability: "local",
    input: "embedding",
    notes: "Embedding-only option when multilingual retrieval matters for NodeAgent documents.",
    pull: "ollama pull snowflake-arctic-embed2",
    sourceUrl: "https://ollama.com/library",
  },
];

export const CLOUD_ONLY_REFERENCE_MODELS: LocalModelOption[] = [
  {
    id: "kimi_k2_7_code_cloud",
    label: "Kimi K2.7 Code — latest agentic coder, Ollama cloud-only",
    family: "Moonshot Kimi",
    ollamaModel: "kimi-k2.7-code:cloud",
    parameterSize: "1.04T total",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["code", "nodeagent", "vision"],
    bucket: "cloud_only_reference",
    availability: "cloud_only",
    contextWindow: "256K",
    input: "text_image",
    notes: "Included only so the UI is honest: it is very current, but Ollama exposes it as cloud-only, so it is not a free local dropdown default.",
    pull: "ollama run kimi-k2.7-code:cloud",
    sourceUrl: "https://ollama.com/library/kimi-k2.7-code",
  },
  {
    id: "kimi_k2_5_cloud",
    label: "Kimi K2.5 — multimodal agentic model, Ollama cloud-only",
    family: "Moonshot Kimi",
    ollamaModel: "kimi-k2.5:cloud",
    parameterSize: "cloud-only",
    hardwareTier: "cloud_or_lab",
    recommendedFor: ["code", "nodeagent", "vision"],
    bucket: "cloud_only_reference",
    availability: "cloud_only",
    contextWindow: "256K",
    input: "text_image",
    notes: "Current and relevant, but not local in Ollama; excluded from the runnable local selects.",
    pull: "ollama run kimi-k2.5:cloud",
    sourceUrl: "https://ollama.com/library/kimi-k2.5",
  },
];

export const DEFAULT_VOICE_MODEL_ID = "gemma4_e2b";
export const DEFAULT_NODEAGENT_MODEL_ID = "gemma4_12b";

export function getLocalModelById(id: string | undefined, fallbackId = DEFAULT_VOICE_MODEL_ID): LocalModelOption {
  return LOCAL_MODEL_OPTIONS.find((model) => model.id === id || model.ollamaModel === id) ?? LOCAL_MODEL_OPTIONS.find((model) => model.id === fallbackId)!;
}

export function getOllamaModelName(idOrName: string | undefined, fallbackId = DEFAULT_VOICE_MODEL_ID): string {
  return getLocalModelById(idOrName, fallbackId).ollamaModel;
}

export function getModelsFor(use: LocalModelUse): LocalModelOption[] {
  return LOCAL_MODEL_OPTIONS.filter((model) => model.recommendedFor.includes(use) && model.availability !== "cloud_only");
}

export function getModelsByBucket(bucket: ModelBucket): LocalModelOption[] {
  return LOCAL_MODEL_OPTIONS.filter((model) => model.bucket === bucket);
}
